# server
server:
  port: '8088'

# spring
spring:
  h2:
    console:
      path: '/h2/console'
      enabled: 'true'
  datasource:
    driver-class-name: 'org.h2.Driver'
#    schema: 'classpath:/h2-sql/schema.sql'
#    data: 'classpath:h2-sql/data.sql'
    url: 'jdbc:h2:mem:support'
    username: 'admin'
    password: 'admin'
    initialization-mode: 'always'