# server
server:
  port: '8088'

# spring
spring:
  druid:
    database: 'h2'
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:mem:support'
    username: 'admin'
    password: 'admin'
  h2:
    console:
      path: '/h2/console'
      enabled: 'true'
  sql:
    init:
      encoding: 'utf-8'
      mode: 'always'
      platform: 'h2'
      schema-locations:
        - 'classpath:dll/schema.sql'