# spring
spring:
  application:
    name: 'Support-svc'

# mybatis
mybatis:
  configuration:
    mp-underscore-to-camel-case: 'true'
    log-impl: 'org.apache.ibatis.logging.stdout.StdOutImpl'

# meowu
meowu:
  web:
    cors: 'true'
    converter: 'gson'

# logging
logging:
  config: 'classpath:logback-spring.xml'